package com.aishang.rulemanager.dal.model;

public class LoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.login_at
     *
     * @mbg.generated
     */
    private Long loginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.ipAddr
     *
     * @mbg.generated
     */
    private String ipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbg.generated
     */
    public LoginLog(Integer id, String username, String realName, Integer type, Long loginAt, String ipaddr, Integer result) {
        this.id = id;
        this.username = username;
        this.realName = realName;
        this.type = type;
        this.loginAt = loginAt;
        this.ipaddr = ipaddr;
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbg.generated
     */
    public LoginLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.id
     *
     * @return the value of login_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.id
     *
     * @param id the value for login_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.username
     *
     * @return the value of login_log.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.username
     *
     * @param username the value for login_log.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.real_name
     *
     * @return the value of login_log.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.real_name
     *
     * @param realName the value for login_log.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.type
     *
     * @return the value of login_log.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.type
     *
     * @param type the value for login_log.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.login_at
     *
     * @return the value of login_log.login_at
     *
     * @mbg.generated
     */
    public Long getLoginAt() {
        return loginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.login_at
     *
     * @param loginAt the value for login_log.login_at
     *
     * @mbg.generated
     */
    public void setLoginAt(Long loginAt) {
        this.loginAt = loginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.ipAddr
     *
     * @return the value of login_log.ipAddr
     *
     * @mbg.generated
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.ipAddr
     *
     * @param ipaddr the value for login_log.ipAddr
     *
     * @mbg.generated
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr == null ? null : ipaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.result
     *
     * @return the value of login_log.result
     *
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.result
     *
     * @param result the value for login_log.result
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }
}