package com.aishang.rulemanager.dal.model;

public class OperationLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.uri
     *
     * @mbg.generated
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.operated_at
     *
     * @mbg.generated
     */
    private Long operatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbg.generated
     */
    public OperationLog(Integer id, String method, String uri, String operator, Long operatedAt) {
        this.id = id;
        this.method = method;
        this.uri = uri;
        this.operator = operator;
        this.operatedAt = operatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbg.generated
     */
    public OperationLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.id
     *
     * @return the value of operation_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.id
     *
     * @param id the value for operation_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.method
     *
     * @return the value of operation_log.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.method
     *
     * @param method the value for operation_log.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.uri
     *
     * @return the value of operation_log.uri
     *
     * @mbg.generated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.uri
     *
     * @param uri the value for operation_log.uri
     *
     * @mbg.generated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.operator
     *
     * @return the value of operation_log.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.operator
     *
     * @param operator the value for operation_log.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.operated_at
     *
     * @return the value of operation_log.operated_at
     *
     * @mbg.generated
     */
    public Long getOperatedAt() {
        return operatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.operated_at
     *
     * @param operatedAt the value for operation_log.operated_at
     *
     * @mbg.generated
     */
    public void setOperatedAt(Long operatedAt) {
        this.operatedAt = operatedAt;
    }
}