package com.aishang.rulemanager.dal.model;

public class RoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.role_code
     *
     * @mbg.generated
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.resource_code
     *
     * @mbg.generated
     */
    private String resourceCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated
     */
    public RoleResource(Integer id, String roleCode, String resourceCode) {
        this.id = id;
        this.roleCode = roleCode;
        this.resourceCode = resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated
     */
    public RoleResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.id
     *
     * @return the value of role_resource.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.id
     *
     * @param id the value for role_resource.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.role_code
     *
     * @return the value of role_resource.role_code
     *
     * @mbg.generated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.role_code
     *
     * @param roleCode the value for role_resource.role_code
     *
     * @mbg.generated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.resource_code
     *
     * @return the value of role_resource.resource_code
     *
     * @mbg.generated
     */
    public String getResourceCode() {
        return resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.resource_code
     *
     * @param resourceCode the value for role_resource.resource_code
     *
     * @mbg.generated
     */
    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode == null ? null : resourceCode.trim();
    }
}